export type Profile = {
  id: string | number;
  name: string;
  age?: number;
  location?: string;
  image: any;
  photos?: { uri: string; thumbnail?: string }[];
  compatibility?: number;
  astrology_score?: number;
  personality_score?: number;
  compatibility_note?: string;
  indian_score?: number;
  western_score?: number;
  indian_recommendation?: string | null;
  western_report?: string | null;
  about_me?: string;
  interests?: string[];
  western_sign?: string;
  indian_sign?: string;
  sun_sign_harmony?: string;
  moon_sign_alignment?: string;
  final_score?: number;
  looking_for?: string;
  relationship_status?: string;
  hobbies?: string[];
  height?: string;
  introvert_extrovert?: string;
  partner_preference?: string[];
  gender?: string;
  gender_detail?: string;
  personality_detail?: {
    date_type?: string[];
    unusual_foods?: string;
    conversations?: string;
    planning_style?: string;
    commitments?: string;
    workspace?: string;
    spend_time?: string;
    energy_level?: string;
    partner_energy?: string;
    arguments?: string;
    show_care?: string;
    partner_type?: string;
    late_reply?: string;
    emotional_handling?: string;
    overthink?: string;
  };
};
